######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : advanced_bioconductor_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : cleanup_advanced_bioconductor_workflow_0_local.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=e872a632-57bc-4312-ac22-37b83851a42e PEGASUS_WF_LABEL=advanced_bioconductor_workflow PEGASUS_DAG_JOB_ID=cleanup_advanced_bioconductor_workflow_0_local PEGASUS_SITE=local "
arguments = " -n pegasus::cleanup -N null -i - -R local  -L advanced_bioconductor_workflow -T 2016-07-29T16:20:33-07:00 /usr/bin/../bin/pegasus-transfer "
copy_to_spool = false
error = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0002/cleanup_advanced_bioconductor_workflow_0_local.err
executable = /usr/bin/../bin/pegasus-kickstart
input = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0002/cleanup_advanced_bioconductor_workflow_0_local.in
log = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0002/advanced_bioconductor_workflow-0.log
notification = NEVER
output = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0002/cleanup_advanced_bioconductor_workflow_0_local.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 1000
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "e872a632-57bc-4312-ac22-37b83851a42e"
+pegasus_wf_uuid = "e872a632-57bc-4312-ac22-37b83851a42e"
+pegasus_version = "4.6.1"
+pegasus_wf_name = "advanced_bioconductor_workflow-0"
+pegasus_wf_time = "20160729T162038-0700"
+pegasus_wf_xformation = "pegasus::cleanup"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "cleanup_advanced_bioconductor_workflow_0_local"
+pegasus_job_class = 8
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
