######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : advanced_bioconductor_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : e.corPairs1_ID0000020.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=e872a632-57bc-4312-ac22-37b83851a42e PEGASUS_WF_LABEL=advanced_bioconductor_workflow PEGASUS_DAG_JOB_ID=e.corPairs1_ID0000020 PEGASUS_SITE=local "
arguments = " -n e.corPairs1 -N ID0000020 -R local  -s pair-wise-correlations.csv=pair-wise-correlations.csv -s hsc-data.rds=hsc-data.rds -s hsc-cor.tsv=hsc-cor.tsv -s heatmap.jpg=heatmap.jpg -s correlated-genes-1.csv=correlated-genes-1.csv -s gene-pairs-1.csv=gene-pairs-1.csv -s pca-tSNE-plots.jpg=pca-tSNE-plots.jpg -L advanced_bioconductor_workflow -T 2016-07-29T16:20:33-07:00 /scratch/r-home/advanced_workflow/correlate-pairs-1.R "
copy_to_spool = false
error = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0002/e.corPairs1_ID0000020.err
executable = /usr/bin/../bin/pegasus-kickstart
initialdir = /scratch/pegasus-scratch/samrat/pegasus/advanced_bioconductor_workflow/run0002
log = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0002/advanced_bioconductor_workflow-0.log
notification = NEVER
output = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0002/e.corPairs1_ID0000020.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 80
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "e872a632-57bc-4312-ac22-37b83851a42e"
+pegasus_wf_uuid = "e872a632-57bc-4312-ac22-37b83851a42e"
+pegasus_version = "4.6.1"
+pegasus_wf_name = "advanced_bioconductor_workflow-0"
+pegasus_wf_time = "20160729T162038-0700"
+pegasus_wf_xformation = "e.corPairs1"
+pegasus_wf_dax_job_id = "ID0000020"
+pegasus_wf_dag_job_id = "e.corPairs1_ID0000020"
+pegasus_job_class = 1
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
