######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : advanced_bioconductor_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : e.logExp1_ID0000018.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=26ce8d2d-fe57-41d9-ac0c-a6ad771a6274 PEGASUS_WF_LABEL=advanced_bioconductor_workflow PEGASUS_DAG_JOB_ID=e.logExp1_ID0000018 PEGASUS_SITE=local "
arguments = " -n e.logExp1 -N ID0000018 -R local  -s top-hvgs.csv=top-hvgs.csv -s hsc-hvg.tsv=hsc-hvg.tsv -s normalized-log-expression.jpg=normalized-log-expression.jpg -s top.hvgs.RData=top.hvgs.RData -s log-expression-1.jpg=log-expression-1.jpg -L advanced_bioconductor_workflow -T 2016-08-01T09:57:35-07:00 /scratch/r-home/advanced_workflow/log-expression-1.R "
copy_to_spool = false
error = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0003/e.logExp1_ID0000018.err
executable = /usr/bin/../bin/pegasus-kickstart
initialdir = /scratch/pegasus-scratch/samrat/pegasus/advanced_bioconductor_workflow/run0003
log = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0003/advanced_bioconductor_workflow-0.log
notification = NEVER
output = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0003/e.logExp1_ID0000018.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 70
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "26ce8d2d-fe57-41d9-ac0c-a6ad771a6274"
+pegasus_wf_uuid = "26ce8d2d-fe57-41d9-ac0c-a6ad771a6274"
+pegasus_version = "4.6.1"
+pegasus_wf_name = "advanced_bioconductor_workflow-0"
+pegasus_wf_time = "20160801T095754-0700"
+pegasus_wf_xformation = "e.logExp1"
+pegasus_wf_dax_job_id = "ID0000018"
+pegasus_wf_dag_job_id = "e.logExp1_ID0000018"
+pegasus_job_class = 1
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
