######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : advanced_bioconductor_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : e.lrt_ID0000024.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=26ce8d2d-fe57-41d9-ac0c-a6ad771a6274 PEGASUS_WF_LABEL=advanced_bioconductor_workflow PEGASUS_DAG_JOB_ID=e.lrt_ID0000024 PEGASUS_SITE=local "
arguments = " -n e.lrt -N ID0000024 -R local  -s brain-marker-2.tsv=brain-marker-2.tsv -s markers.csv=markers.csv -s cluster2-heatmap.jpg=cluster2-heatmap.jpg -L advanced_bioconductor_workflow -T 2016-08-01T09:57:35-07:00 /scratch/r-home/advanced_workflow/LRT.R  hvgs-setup-2.sce.RData "
copy_to_spool = false
error = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0003/e.lrt_ID0000024.err
executable = /usr/bin/../bin/pegasus-kickstart
initialdir = /scratch/pegasus-scratch/samrat/pegasus/advanced_bioconductor_workflow/run0003
log = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0003/advanced_bioconductor_workflow-0.log
notification = NEVER
output = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0003/e.lrt_ID0000024.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 90
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "26ce8d2d-fe57-41d9-ac0c-a6ad771a6274"
+pegasus_wf_uuid = "26ce8d2d-fe57-41d9-ac0c-a6ad771a6274"
+pegasus_version = "4.6.1"
+pegasus_wf_name = "advanced_bioconductor_workflow-0"
+pegasus_wf_time = "20160801T095754-0700"
+pegasus_wf_xformation = "e.lrt"
+pegasus_wf_dax_job_id = "ID0000024"
+pegasus_wf_dag_job_id = "e.lrt_ID0000024"
+pegasus_job_class = 1
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
