######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : advanced_bioconductor_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : e.qc1.2_ID0000004.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=26ce8d2d-fe57-41d9-ac0c-a6ad771a6274 PEGASUS_WF_LABEL=advanced_bioconductor_workflow PEGASUS_DAG_JOB_ID=e.qc1.2_ID0000004 PEGASUS_SITE=local "
arguments = " -n e.qc1.2 -N ID0000004 -R local  -s library-sizes-2.jpg=library-sizes-2.jpg -s expressed-genes-2.jpg=expressed-genes-2.jpg -L advanced_bioconductor_workflow -T 2016-08-01T09:57:35-07:00 /scratch/r-home/advanced_workflow/quality-control-1.R  sce-countLoading.RData  1e3  library-sizes-2.jpg   expressed-genes-2.jpg "
copy_to_spool = false
error = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0003/e.qc1.2_ID0000004.err
executable = /usr/bin/../bin/pegasus-kickstart
initialdir = /scratch/pegasus-scratch/samrat/pegasus/advanced_bioconductor_workflow/run0003
log = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0003/advanced_bioconductor_workflow-0.log
notification = NEVER
output = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0003/e.qc1.2_ID0000004.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 30
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "26ce8d2d-fe57-41d9-ac0c-a6ad771a6274"
+pegasus_wf_uuid = "26ce8d2d-fe57-41d9-ac0c-a6ad771a6274"
+pegasus_version = "4.6.1"
+pegasus_wf_name = "advanced_bioconductor_workflow-0"
+pegasus_wf_time = "20160801T095754-0700"
+pegasus_wf_xformation = "e.qc1.2"
+pegasus_wf_dax_job_id = "ID0000004"
+pegasus_wf_dag_job_id = "e.qc1.2_ID0000004"
+pegasus_job_class = 1
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
