######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : advanced_bioconductor_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : e.hvgs2_ID0000017.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=9ff49b0e-c6a8-4608-93e9-0e114b8641d3 PEGASUS_WF_LABEL=advanced_bioconductor_workflow PEGASUS_DAG_JOB_ID=e.hvgs2_ID0000017 PEGASUS_SITE=local "
arguments = " -n e.hvgs2 -N ID0000017 -R local  -s tSNE-tissue-sex.jpg=tSNE-tissue-sex.jpg -s var.out-2.RData=var.out-2.RData -s C1-chip-colored.jp=C1-chip-colored.jp -s var.fit-2.RData=var.fit-2.RData -s hvgs-setup-2.sce.RData=hvgs-setup-2.sce.RData -s pca-tissue-sex.jpg=pca-tissue-sex.jpg -L advanced_bioconductor_workflow -T 2016-08-01T10:22:29-07:00 /scratch/r-home/advanced_workflow/HVGs-setup-2.R  normalize2-sce.RData   hvgs-setup-2.sce.RData "
copy_to_spool = false
error = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0004/e.hvgs2_ID0000017.err
executable = /usr/bin/../bin/pegasus-kickstart
initialdir = /scratch/pegasus-scratch/samrat/pegasus/advanced_bioconductor_workflow/run0004
log = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0004/advanced_bioconductor_workflow-0.log
notification = NEVER
output = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0004/e.hvgs2_ID0000017.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 60
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "9ff49b0e-c6a8-4608-93e9-0e114b8641d3"
+pegasus_wf_uuid = "9ff49b0e-c6a8-4608-93e9-0e114b8641d3"
+pegasus_version = "4.6.1"
+pegasus_wf_name = "advanced_bioconductor_workflow-0"
+pegasus_wf_time = "20160801T102233-0700"
+pegasus_wf_xformation = "e.hvgs2"
+pegasus_wf_dax_job_id = "ID0000017"
+pegasus_wf_dag_job_id = "e.hvgs2_ID0000017"
+pegasus_job_class = 1
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
