######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : advanced_bioconductor_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : register_local_8_1.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=9ff49b0e-c6a8-4608-93e9-0e114b8641d3 PEGASUS_WF_LABEL=advanced_bioconductor_workflow PEGASUS_DAG_JOB_ID=register_local_8_1 PEGASUS_SITE=local "
arguments = " -n pegasus::rc-client -N null -R local  -L advanced_bioconductor_workflow -T 2016-08-01T10:22:29-07:00 /usr/bin/pegasus-rc-client --conf /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0004/pegasus.4539901559891327210.properties -v --insert /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0004/register_local_8_1.in"
copy_to_spool = false
error = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0004/register_local_8_1.err
executable = /usr/bin/../bin/pegasus-kickstart
getenv = true
log = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0004/advanced_bioconductor_workflow-0.log
notification = NEVER
output = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0004/register_local_8_1.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 120
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "9ff49b0e-c6a8-4608-93e9-0e114b8641d3"
+pegasus_wf_uuid = "9ff49b0e-c6a8-4608-93e9-0e114b8641d3"
+pegasus_version = "4.6.1"
+pegasus_wf_name = "advanced_bioconductor_workflow-0"
+pegasus_wf_time = "20160801T102233-0700"
+pegasus_wf_xformation = "pegasus::rc-client"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "register_local_8_1"
+pegasus_job_class = 4
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
