######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : advanced_bioconductor_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : e.cellBlock_ID0000022.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=7fa97524-6389-4a78-842d-879f10d8d883 PEGASUS_WF_LABEL=advanced_bioconductor_workflow PEGASUS_DAG_JOB_ID=e.cellBlock_ID0000022 PEGASUS_SITE=local "
arguments = " -n e.cellBlock -N ID0000022 -R local  -s phase-scores.jpg=phase-scores.jpg -s cell-cycle-removal.jpg=cell-cycle-removal.jpg -s normalization-vs-deconvolution.jpg=normalization-vs-deconvolution.jpg -s diffusion-map.jpg=diffusion-map.jpg -s cell.cycle.blocking.sce.RData=cell.cycle.blocking.sce.RData -L advanced_bioconductor_workflow -T 2016-07-29T15:45:59-07:00 /scratch/r-home/advanced_workflow/cell-cycle-blocking.R  cell.cycle.blocking.sce.RData "
copy_to_spool = false
error = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0001/e.cellBlock_ID0000022.err
executable = /usr/bin/../bin/pegasus-kickstart
initialdir = /scratch/pegasus-scratch/samrat/pegasus/advanced_bioconductor_workflow/run0001
log = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0001/advanced_bioconductor_workflow-0.log
notification = NEVER
output = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0001/e.cellBlock_ID0000022.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 90
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "7fa97524-6389-4a78-842d-879f10d8d883"
+pegasus_wf_uuid = "7fa97524-6389-4a78-842d-879f10d8d883"
+pegasus_version = "4.6.1"
+pegasus_wf_name = "advanced_bioconductor_workflow-0"
+pegasus_wf_time = "20160729T154610-0700"
+pegasus_wf_xformation = "e.cellBlock"
+pegasus_wf_dax_job_id = "ID0000022"
+pegasus_wf_dag_job_id = "e.cellBlock_ID0000022"
+pegasus_job_class = 1
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
