######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : advanced_bioconductor_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : e.corPairs2_ID0000021.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=7fa97524-6389-4a78-842d-879f10d8d883 PEGASUS_WF_LABEL=advanced_bioconductor_workflow PEGASUS_DAG_JOB_ID=e.corPairs2_ID0000021 PEGASUS_SITE=local "
arguments = " -n e.corPairs2 -N ID0000021 -R local  -s dispersion-summary.csv=dispersion-summary.csv -s y.Rdata=y.Rdata -s clust.col.Rdata=clust.col.Rdata -s cluster.Rdata=cluster.Rdata -s my.tree.Rdata=my.tree.Rdata -s brain.heat.pdf=brain.heat.pdf -s design.Rdata=design.Rdata -s fit.Rdata=fit.Rdata -s my.clusters.Rdata=my.clusters.Rdata -L advanced_bioconductor_workflow -T 2016-07-29T15:45:59-07:00 /scratch/r-home/advanced_workflow/correlate-pairs-2.R  hvgs-setup-2.sce.RData "
copy_to_spool = false
error = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0001/e.corPairs2_ID0000021.err
executable = /usr/bin/../bin/pegasus-kickstart
initialdir = /scratch/pegasus-scratch/samrat/pegasus/advanced_bioconductor_workflow/run0001
log = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0001/advanced_bioconductor_workflow-0.log
notification = NEVER
output = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0001/e.corPairs2_ID0000021.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 80
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "7fa97524-6389-4a78-842d-879f10d8d883"
+pegasus_wf_uuid = "7fa97524-6389-4a78-842d-879f10d8d883"
+pegasus_version = "4.6.1"
+pegasus_wf_name = "advanced_bioconductor_workflow-0"
+pegasus_wf_time = "20160729T154610-0700"
+pegasus_wf_xformation = "e.corPairs2"
+pegasus_wf_dax_job_id = "ID0000021"
+pegasus_wf_dag_job_id = "e.corPairs2_ID0000021"
+pegasus_job_class = 1
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
