######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : advanced_bioconductor_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : e.lowabundance1.1_ID0000009.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=7fa97524-6389-4a78-842d-879f10d8d883 PEGASUS_WF_LABEL=advanced_bioconductor_workflow PEGASUS_DAG_JOB_ID=e.lowabundance1.1_ID0000009 PEGASUS_SITE=local "
arguments = " -n e.lowabundance1.1 -N ID0000009 -R local  -s lowAbundance-sce-1.RData=lowAbundance-sce-1.RData -s freq-vs-mean-1.jpg=freq-vs-mean-1.jpg -s alt.keep-1.txt=alt.keep-1.txt -s keep-1.txt=keep-1.txt -L advanced_bioconductor_workflow -T 2016-07-29T15:45:59-07:00 /scratch/r-home/advanced_workflow/low-abundance-filter.R  sce-filters-1.RData   keep-1.txt   lowAbundance-sce-1.RData   alt.keep-1.txt   freq-vs-mean-1.jpg "
copy_to_spool = false
error = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0001/e.lowabundance1.1_ID0000009.err
executable = /usr/bin/../bin/pegasus-kickstart
initialdir = /scratch/pegasus-scratch/samrat/pegasus/advanced_bioconductor_workflow/run0001
log = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0001/advanced_bioconductor_workflow-0.log
notification = NEVER
output = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0001/e.lowabundance1.1_ID0000009.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 40
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "7fa97524-6389-4a78-842d-879f10d8d883"
+pegasus_wf_uuid = "7fa97524-6389-4a78-842d-879f10d8d883"
+pegasus_version = "4.6.1"
+pegasus_wf_name = "advanced_bioconductor_workflow-0"
+pegasus_wf_time = "20160729T154610-0700"
+pegasus_wf_xformation = "e.lowabundance1.1"
+pegasus_wf_dax_job_id = "ID0000009"
+pegasus_wf_dag_job_id = "e.lowabundance1.1_ID0000009"
+pegasus_job_class = 1
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
