######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : advanced_bioconductor_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : e.qc2.2_ID0000006.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=7fa97524-6389-4a78-842d-879f10d8d883 PEGASUS_WF_LABEL=advanced_bioconductor_workflow PEGASUS_DAG_JOB_ID=e.qc2.2_ID0000006 PEGASUS_SITE=local "
arguments = " -n e.qc2.2 -N ID0000006 -R local  -s ERCC-prorportion-2.jpg=ERCC-prorportion-2.jpg -s mito-proportion-2.jpg=mito-proportion-2.jpg -L advanced_bioconductor_workflow -T 2016-07-29T15:45:59-07:00 /scratch/r-home/advanced_workflow/quality-control-2.R  sce-countLoading.RData   mito-proportion-2.jpg   ERCC-prorportion-2.jpg "
copy_to_spool = false
error = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0001/e.qc2.2_ID0000006.err
executable = /usr/bin/../bin/pegasus-kickstart
initialdir = /scratch/pegasus-scratch/samrat/pegasus/advanced_bioconductor_workflow/run0001
log = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0001/advanced_bioconductor_workflow-0.log
notification = NEVER
output = /scratch/advanced_bioconductor_workflow/submit/samrat/pegasus/advanced_bioconductor_workflow/run0001/e.qc2.2_ID0000006.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 30
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "7fa97524-6389-4a78-842d-879f10d8d883"
+pegasus_wf_uuid = "7fa97524-6389-4a78-842d-879f10d8d883"
+pegasus_version = "4.6.1"
+pegasus_wf_name = "advanced_bioconductor_workflow-0"
+pegasus_wf_time = "20160729T154610-0700"
+pegasus_wf_xformation = "e.qc2.2"
+pegasus_wf_dax_job_id = "ID0000006"
+pegasus_wf_dag_job_id = "e.qc2.2_ID0000006"
+pegasus_job_class = 1
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
